some adjustments to work on ubuntu

diff --git a/makelatex b/makelatex
--- a/makelatex
+++ b/makelatex
@@ -4,10 +4,10 @@
 # bibtex stuff
 #
 pdflatex -shell-escape -draftmode -halt-on-error 0_researchnotes.tex
-if [ $? -ne 0 ]; then
-    echo "Compilation failed! Rerun with makelatex to learn more."
-    exit
-fi
+#if [ $? -ne 0 ]; then
+#    echo "Compilation failed! Rerun with makelatex to learn more."
+#    exit
+#fi
 for auxfile in ch_*.aux; do
     bibtex `basename $auxfile .aux`
 done
@@ -28,7 +28,7 @@ done
 #
 pdflatex -interaction=batchmode -shell-escape -draftmode 0_researchnotes.tex > /dev/null 2>&1
 makeindex -s indexHeader.ist 0_researchnotes
-python scripts/fixIndex.py
+python3 scripts/fixIndex.py
 mv temp.idx 0_researchnotes.idx
 mv temp.ind 0_researchnotes.ind
 pdflatex -interaction=batchmode -shell-escape -draftmode 0_researchnotes.tex > /dev/null 2>&1
